name: Compile and Release Qt6 Project
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.0.0  
    - name: Install Qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        host: windows
        target: desktop
        version: 6.5.2
        arch: win64_mingw
        dir: ${{github.workspace}}/qt
        modules: qtmultimedia
        cache: true
        cache-key-prefix: install-qt
    - name: Configure CMake Project
      working-directory: ${{github.workspace}}
      run: cmake -DCMAKE_BUILD_TYPE=Release -DTESTING=ON -G "CodeBlocks - MinGW Makefiles" -B ${{github.workspace}}\build
    - name: Build project
      working-directory: ${{github.workspace}}\build
      run: mingw32-make.exe
    - name: Find tests
      uses: mathiasvr/command-output@v2.0.0
      id: tests
      with:
        shell: powershell
        run: dir "${{github.workspace}}/build/MindMate-Windows" -Filter "*Test.exe" | Select-Object -ExpandProperty FullName
    - name: Run tests
      run: |
        $filesList = "${{steps.tests.outputs.stdout}}" -split [Environment]::NewLine
        foreach ($file in $filesList) { Invoke-Expression -Command "& '$file'" }    
