name: Unit testing
on: workflow_dispatch
jobs:
  Install-LLVM_Clang:
    runs-on: ubuntu-latest
    steps:
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.8.3
      with:
        version: "13.0"
  Install-Qt:
    needs: Install-LLVM_Clang
    runs-on: ubuntu-latest
    steps:
    - name: Install Qt static
      uses: anthepro/install-qt-static@v1
      with:
        version: 6.5.0
        configure-args: -opensource -opengl desktop
        submodules: qtbase,qtsvg,qtshadertools,qtdeclarative,qtmultimedia,qttools,qttranslations
  Build:
    needs: Install-Qt
    runs-on: ubuntu-latest
    steps: 
    - name: Get repository code
      uses: actions/checkout@v4.0.0
    - name: Build
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-type: MinSizeRel
        configure-options: -DTESTING=ON
        
