name: Unit testing
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: ==3.1.*
        version: 6.5.0
        host: linux
        target: desktop
        arch: gcc_64
        modules: qtmultimedia
        cache: true
        cache-key-prefix: install-qt
    - name: Get repository code
      uses: actions/checkout@v4.0.0
    - name: Build
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-type: Release
        configure-options: -DTESTING=ON
    - name: Run tests
      run: |
        find ./build -type f -name "*Test" -exec echo {}
