name: Unit testing
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - name: Setup display
      run: |
        sudo apt-get install libxcb-xinerama0
        sudo apt-get install libxcb-xinput0
        sudo apt-get install libxcb* 
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        export DISPLAY=:99
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: ==3.1.*
        version: 6.5.0
        host: linux
        target: desktop
        arch: gcc_64
        modules: qtmultimedia
        cache: true
        cache-key-prefix: install-qt
    - name: Get repository code
      uses: actions/checkout@v4.0.0
    - name: Build
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-type: Release
        configure-options: -DTESTING=ON -DQT_DEBUG_PLUGINS=1
    - name: Find tests
      uses: mathiasvr/command-output@v2.0.0
      id: tests
      with:
        run: find ${{ runner.workspace }}/build/ -type f -name "*Test"   
    - name: Run tests
      run: ${{ steps.tests.outputs.stdout }}
#- run: echo Today is ${{ steps.today.outputs.stdout }}
 #   - name: Run tests
 #     run: find ${{ runner.workspace }}/build/ -type f -name "*Test" -exec {} \;
